# Generated by Django 3.1.2 on 2020-11-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Electronic', 'Electronic')], max_length=250, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='main.Tag')),
            ],
        ),
    ]
